#!/usr/bin/perl
# By Chi-Hang Lam (2018-02-15)
# av [-e] [-a] [files ...]      
#    -sd     : sd mode, i.e. sd(x) not sd(x)/sqrt(n) is calculated with -e
#    -e[n]   : calculate errors in n-th column
#            : eg -e2 =>  x1, x2, dx2, x3, ...
#    -e      : equivalent to -e2
#    -min[n] : minimun in n-th column
#    -max[n] : maximun in n-th column
#        (eg. -e2 -min2 -max2 (in any order) => x1, x2, dx2, xmin2 , xmax2 ...)
#    -a      : average over all rows for files with different lengths
#    -g<n>   : subgrouping files into subgroups of n
#    -o<fname> : file name
#    -c<n>   : coarsen by averaging every n rows
#    -C<r>[,<n>]   : coarsen by averaging every n rows, n *= r after every row
#                    initial n=1 if not supplied
#
# ENVIRONMENTAL VARIABLES:        AV_QUIET
# Output:
#    e.g. Columns= 1<-x1   , i.e. column 1 in new files given by column 1 in old file
#
#endcomments

# 25 Apr  readfile speeded up,
#         weight implemented (except for error calculations!)
# 25 Jun 2004, problem with filename containing '-' fixed
use List::Util qw(min max);
$truncate=1;
$indexed=1;
$empty=1e99;
$groupsize=10000;
$subrowsize=1;
$minimum=0;
$groupcnt=1;
$ncol=0;
$subrowr=0;
$row=0;

sub subrowsizecal{
    if ($subrowr>0){
        $subrowsize=int($subrow0*$subrowr**$row);
    }
}

if ( !defined $ARGV[0] ) { print_help(); die "\n";}
while (@ARGV){
    if ($ARGV[0] =~ /^-/){
        if    ($ARGV[0] =~ /^-sd$/)      { $SD=1; }
        elsif ($ARGV[0] =~ /^-e(\d+)$/)  { $calerr[$1]=1; }
        elsif ($ARGV[0] =~ /^-e$/)       { $calerr[2]=1; }
        elsif ($ARGV[0] =~ /^-min(\d+)$/){ $minimum[$1]=1; }
        elsif ($ARGV[0] =~ /^-max(\d+)$/){ $maximum[$1]=1; }
        elsif ($ARGV[0] =~ /^-a$/)       { $truncate=0; }
        elsif ($ARGV[0] =~ /^-g(\S+)$/)  { $groupsize=$1; }
        elsif ($ARGV[0] =~ /^-c(\S+)$/)  { $subrowsize=$1; }
        elsif ($ARGV[0] =~ /^-C(\S+)$/)  {
            $subrowr=$1; $subrow0=1;
            if ($subrowr =~ /(\S+),(\S+)/){
                $subrowr=$1; $subrow0=$2;
            }
            subrowsizecal(); 
        }
        elsif ($ARGV[0] =~ /^-o(\S+)$/)  { $fname=$1; }
        else { print "$0: unknown option (ignored): $ARGV[0]\n"; }
        shift;
    }else{
        last;
    }
}

while (@ARGV){			# loop until all subgroups are done
    if (!($ARGV[0] =~ /^-/)){
        avfile();
    }
}

sub avfile{
    if (defined $fname){
        $fout="$fname-$groupcnt.av";
    }else{
        $f="$ARGV[0]";		# output file name based on first file in subgroup
        if ($f =~ /\?/){ die "Problematic file name: $f\n"; }
        $fout="$f.av";
        $fout =~ s/set(\d+)\///;
    }
    $nfile=0;
    $nrow=0;
    $filecnt=0;
    @filelist=@ARGV;

    # read files
    for $gname (@filelist){	# loop over files in subgroup
        shift @ARGV;
#    if ( (-r "set1/$gname")||(-r "set2/$gname")||(-r "set3/$gname")){
#      $grouplist=`ls $gname set*/$gname`;
#    }else{
        $grouplist="$gname";
#    }
        @grouplist=split(/\n/,"$grouplist");
        #printf "@grouplist\n";
        for $f (@grouplist){
            readfile();
        }
        ++$filecnt;
        if ($filecnt==$groupsize){++$groupcnt; last;} #next group
    }
    writefile();
}

sub endblock(){
    if ($truncate==0 && $subrow>0){ ++ $row;}
    if ($row>0){
        if ($nfile==1){ 
            $nrow[$block]=$row;
        }else{
            if ($truncate==1){
                if ($row<$nrow[$block]){ $nrow[$block]=$row;}
            }else{  
                if ($row>$nrow[$block]){ $nrow[$block]=$row;}
            }
        }
        ++$block;
        $row_last=$row;
        $subrow=$row=0;
        subrowsizecal();
    }
}

sub readfile(){
    local $x;
    if (open(infile,"<$f")){
        ++$nfile;
        if ( !defined $ENV{AV_QUIET}) {print "Input($nfile)  =  $f";}
        $block=$row=$subrow=0;
        $FileWeight=1;

        while (<infile>) {		# read current file
            if ( /^\#/ ){ # comment line
                if ($block==0 && $row==0 && /^\#weight=(\S+)/){
                    $FileWeight=$1;
                    if ( !defined $ENV{AV_QUIET}) {print "     weight = $FileWeight";}
                }
            }elsif ( /(\S+)/ ) {		# data line
                $col=0;
                for $x (split) {	# read all columns
                    ++$col;
                    if ($col>=$ncol){ $ncol=$col; }

                    if ($minimum[$col]){
                        if ($x<$min[$block][$row][$col] || ($nfile==1 && $subrow==0) ) {
                            $min[$block][$row][$col]=$x;
                        }
                    }
                    if ($maximum[$col]){
                        if ($x>$max[$block][$row][$col] ||  ($nfile==1 && $subrow==0) ) {
                            $max[$block][$row][$col]=$x;
                        }
                    }

                    if ($FileWeight!=1){ $x*=$FileWeight; }

                    $xs[$block][$row][$col]+=$x;
                    if ($calerr[$col]){
                        $xs2[$block][$row][$col]+=$x*$x;
                    }
                }
                $n[$block][$row]+=$FileWeight;	# increment no. of sample for this row
                ++$subrow;
                if ($subrow==$subrowsize){ 
                    ++$row; $subrow=0; 
                    subrowsizecal();
                }
            }else{			#blank line
                endblock();
            }
        }
        endblock();
        close(infile);
        #if ($row>0) {++$block;}	# last block ended by EOF
        if ( !defined $ENV{AV_QUIET}) {print "   ($ncol cols $row_last rows $block blocks)\n"; }
        if ($nfile==1) { $nblock=$block;}
        else{
            if ($truncate==1){if ($block<$nblock){ $nblock=$block;}}
            else{             if ($block>$nblock){ $nblock=$block;}}
        }
    }
}

sub columninfo{
    if ((!defined $ENV{AV_QUIET})&&($block==0)&&($row==0)){
        printf "$outputcol<-@_$col  "; }
    ++$outputcol;
}

sub writefile(){
    open(ofile,">$fout");
    if ( !defined $ENV{AV_QUIET}) {print "Output = $fout\n"; print "Columns= "}
    #printf "$nblock\n";
    for ($block=0; $block<$nblock; ++$block){
        for ($row=0; $row<$nrow[$block]; ++$row){
            if ($n[$block][$row]==0){
                print ofile "\n";
            } else {
                for ($col=1, $outputcol=1; $col<=$ncol; ++$col){
                    # mean
                    $xm=$xs[$block][$row][$col]/$n[$block][$row];
                    printf ofile "%17.10e ",$xm;
                    columninfo("x");

                    # error
                    if ($calerr[$col])  {
                        $err=($xs2[$block][$row][$col]/$n[$block][$row]
                              -$xm*$xm)**0.5;
                        if (! defined $SD){
                            $err = $err/(($n[$block][$row]-1+1e-8)**0.5);
                        }
                        printf ofile "%17.10e ",$err;
                        columninfo("Dx");
                    }
                    # minimum
                    if ($minimum[$col]) {
                        printf ofile "%17.10e ", $min[$block][$row][$col];
                        columninfo("Min");
                    }
                    # maximum
                    if ($maximum[$col]) {
                        printf ofile "%17.10e ", $max[$block][$row][$col];
                        columninfo("Max");
                    }
                }
                printf ofile "\n";
            }
        }
        if ($block<$nblock-1){print ofile "\n";}
    }
    close(ofile);
    printf "\n";

    # clear array for next subgroup
    for ($block=0;$block<$nblock;++$block){
        for ($row=0;$row<$nrow[$block];++$row){
            for ($col=1; $col<=$ncol; ++$col){ 
                $xs[$block][$row][$col]=$xs2[$block][$row][$col]=0;
            }
            $n[$block][$row]=0; 
        }
    }
}

sub print_help{
    $f=`which av`;
    if (open(infile,"<$f")){
        while (<infile>) {
            last if /endcomments/;
            if (/\#/) {print $_;}
        }
    }
}

# vi: ts=4 sw=4
