#!/usr/bin/perl 
# By Chi-Hang Lam (2018-03-06)
#cal [-cmnd] [input file] 
#-cmnd =  
# -q            quiet
# -c1 <c1>      cut first <c1> lines
# -c2 <c2>      cut last <c1> lines
# -nrow <nrow>  take <nrow> lines
# -tail <n>     take last <n> lines
# -transpose
# -leveldown    take last line of each segment
#
# variables: $line (starts from 0)
#            $row  (starts from 0, only count uncut lines)
#            $seg  (starts from 0)
#            $col  (starts from 1)
#            $ncol (no. of columns)
#	         $x[$col], $X[$line][$col]        (data read in)
#            $s[$col], $S[$seg][$line][$col]  (data to be output)
#            $deleteline     (set to 1 if line to be deleted)
#

# Mathematical subroutines: max(x,y) and min(x,y)

sub max ($$) { $_[$_[0] < $_[1]] }
sub min ($$) { $_[$_[0] > $_[1]] }

##########################################

sub log{ 
# -log n     log10 values in column n
$s[$p1]=log($s[$p1])/log(10);
}

sub diff{ 
# -diff   differentiation
    $dn=1;
    if ($line-$dn<0){
      $deleteline=1;
    }else{
      $s[1]=($X[$line][1]+$X[$line-$dn][1])/2.;
      $s[2]=($X[$line][2]-$X[$line-$dn][2])/($X[$line][1]-$X[$line-$dn][1]);
    }
}

sub pow10{
# -pow10 n      10^x for column n
$s[$p1]=10.**$s[$p1];
}

sub pow2{
# -pow2 n      2^x for column n
$s[$p1]=2.**$s[$p1];
}

sub tmp{  $s[1]/=($seg+1)**(2.*0.1756); $s[2]/=($seg+1)**(2.*0.295);}
sub ll{  $s[3]=$s[3]/$s[2]/log(10); 
	 $s[1]=log($s[1])/log(10); $s[2]=log($s[2])/log(10);     }
sub pp{   $s[1]=10**($s[1]); $s[2]=10**($s[2]);     }
sub ln{  $s[1]=log($s[1]); $s[2]=log($s[2]); }
sub id{  ;}

sub del{ 
# -del n     delete colomn n
$ncol-=1; for ($i=$p1; $i<=$ncol; ++$i){ $s[$i]=$s[$i+1]; } 
}

sub nmbr{
# -nmbr      add row number to column 1
$ncol+=1; for ($i=$ncol; $i>=2; --$i){ $s[$i]=$s[$i-1]; } 
$s[1]=$row;
}


sub swap{ 
# -swap n1 n2    swap colomn n1 & n1
  $xtmp=$s[$p1]; $s[$p1]=$s[$p2]; $s[$p2]=$xtmp;
}
#
# -e '<code>'  e.g.     -e 's2+=1'
#              same as: -e '$s[2]+=1' 
#              (all s1, x1 etc. translated to $s[1], $x[1])
#              e.g. -e 'if (row>1 && s1<=S[seg][lastrow][1]){deleteline=1;}'
#                     ( enforce strictly increasing in column 1 )


# integration: int_trap(x,f)         (integrate f(x) using trapeziodal rule))
#
# statistics:
#       data(<x> [,<weight>])             (enter data point)
#       $Sum, $Mean, $Vari, $SD           (statistical measures)
#       sum(<col>[,<weight>])
#       eg. cal -e 'data(x2); s1=Mean; s2=SD' datafile 

sub data{
  if ($row==0){ $Sum=0; $Sum2=0; $Nsample=0;}
  local ($x, $w) = @_;
  if ($x eq ""){ die "Warning: function data requires an input\n";}
  if ($w eq ""){ $w=1; }
  $Sum += $x*$w; $Sum2 += $x*$x*$w;
  $Nsample += $w;
  $Mean = $Sum/$Nsample;
  $Vari = $Sum2/$Nsample - $Mean*$Mean;
  $SD   = $Vari**0.5;
}

sub sum{
  local ($col) = @_;
  data(@_);
  $Sum[$col];
}

sub normxy{
# normalize distribution (s1: x -> x/<x>; s2: p -> p/(dx psum / dx)
    if ($row==0){ $xsum=0; $nsum=0; $xlast=0;}
    local ($x, $n);
    $x=$s[1]; $n=$s[2];
    $xsum += $x*$n;
    $nsum += $n;
    $N[$seg]=$nsum;
    $xmean[$seg] = $xsum/$nsum;
    $dx[$seg] = $x-$xlast;
    $xlast=$x;
}

sub normxy2{ 
    $s[1] = $s[1]/$xmean[$seg];
    $s[2] = $s[2] / ($dx[$seg]*$N[$seg]/$xmean[$seg]);
}

#endcomments

sub int_trap{
  # assume $x is increasing
  local ($x, $f) = @_;
  if ($row==0){
    $In = 0.;
  } else {
    $In += ($Last_f+$f)*($x-$Last_x)/2.;
  }
  $Last_x = $x;
  $Last_f = $f;
  return $In;
}

##################################################################
sub trans_code{
  $code0=$code;
  # conversion
  $code =~ s/\$//g;               # strip all '$'
  $code =~ s/s(\d+)/s[$1]/g;      # s1 -> $s[1] etc
  $code =~ s/x(\d+)/x[$1]/g;      # x1 -> $x[1] etc
  $code =~ s/([a-z_A-Z]+)/\$$1/g; # y  -> $y    etc.
  # to tidy up translated commands
  $code =~ s/  / /g;       
  $code =~ s/; /;/g;
  $code =~ s/;/;\n/g;      
  # back conversion for e, if etc.
  $code =~ s/(\d)\$e([-+\d]+)/$1e$2/g;
  foreach $tran_cmd ('sin','cos','log','exp','if','data','sum','int_trap',
		    'int','abs','max','min'){
    $code =~ s/\$$tran_cmd/$tran_cmd/g;
  }
} 

sub usrcode{
  eval $code;
  printf "$@"; # print error message
}

sub print_help{
$f=`which cal`;
if (open(infile,"<$f")){
	while (<infile>) {
		last if /endcomments/;
	       	if (/\#/) {print $_;}
	    }
    }
}

if ( !defined $ARGV[0] ) { print_help(); die "\n";}
$c1=0; $nrow=1e10; $c2=0;
$paramcnt=0;
while (defined $ARGV[0]) { 
    {
	if ($ARGV[0] eq "-q"){ $quiet=1; shift; last; }
	if ($ARGV[0] eq "-c1"){ shift; $c1=$ARGV[0]; shift; last;}
	if ($ARGV[0] eq "-c2"){ shift; $c2=$ARGV[0]; shift; last;}
	if ($ARGV[0] eq "-tail"){ shift; $tail=$ARGV[0]; shift; last;}
	if ($ARGV[0] eq "-nrow"){ shift; $nrow=$ARGV[0]; shift; last;}
	if ($ARGV[0] eq "-transpose"){ shift; $transpose=1; last;}
	if ($ARGV[0] eq "-transpose1d"){ shift; $transpose1d=1; last;}
	if ($ARGV[0] eq "-normalizexy"){ shift; $normalizexy=1; last;}
	if ($ARGV[0] eq "-leveldown"){ shift; $leveldown=1; $tail=1; last;}
	if ($ARGV[0] eq "-e"){ $cmnd="usrcode"; shift; $code=$ARGV[0]; trans_code(); shift; last;}
	if ($ARGV[0] =~ /-p1/){ shift; $p1=$ARGV[0]; shift; last;}
	foreach $op('ll','pp','ln','e10','id','tmp','mean','sum','diff','sd','nmbr'){
	    if ($ARGV[0] eq "-$op"){
	      $cmnd=$op; 
	      shift; last;
	    };
	}
    foreach $op('normxy'){
	    if ($ARGV[0] eq "-$op"){
	      $cmnd=$op; 
          $cmnd2=$op."2";;
	      shift; last;
	    };
	}
	foreach $op('log','pow10','pow2','del','difference'){
	    if ($ARGV[0] eq "-$op"){
	      $cmnd=$op; shift; 
	      $p1=$ARGV[0]; 
	      shift; last;
	    };
	}
	foreach $op('swap'){
	    if ($ARGV[0] eq "-$op"){
	      $cmnd=$op; shift; 
	      $p1=$ARGV[0]; shift; 
	      $p2=$ARGV[0]; shift; last;
	    };
	}
	if (!defined $f){
	  $f=$ARGV[0]; shift; last; 
	}
	print "unknown argument: $ARGV[0]\n"; shift; last;
    }
}

#if (!defined(&$cmnd)){ die "Unknown command: $cmnd \n";}
if ((!defined $ENV{CAL_QUIET})&&(!defined $quiet)){
    if ($cmnd =~ /usrcode/){ $cmndstr="$code0\nTranslated command:\n$code  ";}  
    else{ $cmndstr=$cmnd; }
    print "Input: $f   Output: $f.r    Command: $cmndstr   ";
    if ($p1 ne ""){ print "p1=$p1 ";}
    print "\n";
}

# Reading ######################

if (!open(infile,"<$f")){ die "Cannot read $f\n";}
if (!open(ofile,">$f.r")){ die "Cannot write $f.r\n";}
$row=0; $line=0; $seg=0;
while (<infile>){
  if (!/^\#/) {
    if ( /(\S+)/ ) {
      $ncol=0;

      # read line
      while ( /(\S+)/ ) {
          ++$ncol;
          $X[$line][$ncol]=$s[$ncol]=$x[$ncol]=$1;
          s/\S+(.*)/$1/e ;	# remove leading entry
      }
      # calculate
      $deleteline=0;

      if (defined(&$cmnd) && (!(eval '&$cmnd()'))) {
      };
      if ( ($line >= $c1) && ($line < ($c1+$nrow))
	   &&($deleteline==0)) {
          $Deleteline[$seg][$row]=$deleteline;
          for ($col=1; $col<=$ncol; ++$col) {
              $S[$seg][$row][$col]=$s[$col];
          }
          $Ncol[$seg][$row]=$ncol;
          $lastrow=$row;
          ++$row;
          $Nrow[$seg]=$row;
      }

      $line++;
      $lastline=$line-1; if ($lastline<0){ $lastline=0; };
      $nseg=$seg+1;

    } else {
        $row=0; $line=0; ++$seg;
    }
  }
}
close(infile);

# Writing ######################

if ($transpose){
  # transpose only, neglecting other operations
  for ($row=0; $row<$Nrow[0]; ++$row){
    for ($seg=0; $seg<$nseg; ++$seg){
      for ($col=1; $col<=$Ncol[$seg][$row]; $col++){
          printf ofile "%.10g ", $S[$seg][$row][$col];
      }
      print ofile "\n"; 
    }
    print ofile "\n"; 
  }
}elsif ($transpose1d){
  # transpose only, neglecting other operations
  for ($seg=0; $seg<$nseg; ++$seg){
    for ($col=1; $col<=$Ncol[$seg][0]; $col++){
      for ($row=0; $row<$Nrow[0]; ++$row){
          printf ofile "%.10g ", $S[$seg][$row][$col];
      }
      print ofile "\n"; 
    }
    print ofile "\n"; 
  }
}else{
  for ($seg=0; $seg<$nseg; ++$seg){
    $lastrow=$Nrow[$seg]-$c2;
    if ($tail==0){
      $firstrow=0;
    }else{
      $firstrow=$lastrow-$tail;
      if ($firstrow<0){$firstrow=0;}
    }
    if ($leveldown && ($firstrow==$lastrow)){ # pad one row of zero if there is no row available
        ++$lastrow;
        $row=$firstrow;
        $Ncol[$seg][$row]=1;
        $S[$seg][$row][$colstart]=0;
    }
    for ($row=$firstrow; $row<$lastrow; ++$row){
      $colstart=1;

      for ($col=$colstart; $col<=$Ncol[$seg][$row]; $col++){
	    $s[$col]=$S[$seg][$row][$col];
      }

      if (defined(&$cmnd2) && (!(eval '$cmnd2()'))) {};

      # if ($leveldown){ $colstart=$Ncol[$seg][$row]; } # don't remember what this line is about
      for ($col=$colstart; $col<=$Ncol[$seg][$row]; $col++){
        # printf ofile "%17.10e ", $S[$seg][$row][$col];
	    printf ofile "%.10g ", $s[$col];
        # printf ofile $S[$seg][$row][$col]; printf ofile "  ";
      }
      if (!$leveldown){ print ofile "\n"; }
    }
    if ($seg<$nseg-1){ print ofile "\n"; }
  }
}
if ($leveldown){ print ofile "\n"; }
close(ofile);

