#!/usr/bin/perl
# By Chi-Hang Lam (2014-1-12)

if (!defined $ARGV[0]){
  print "
Split files into segments

split [-d] [-2 <n>] [<level>] <file> ...
    -d     : output files to file.s directory
    -2 <n> : two dimensional labelling s<i>x<j> with for m x n matrix
    <level>: split after <level> blank lines (<level> = 1 .. 9)

";
exit;
}

$level=1; $DirFlg=$TwoDFlg=0;
while ($ARGV[0] eq "-d" || $ARGV[0] eq "-2"
       || (($ARGV[0] >= 1) && ($ARGV[0] <= 9))){
  if ($ARGV[0] eq "-d"){ $DirFlg=1; shift; }
  if ($ARGV[0] eq "-2"){ $TwoDFlg=1; shift; $TwoDN=$ARGV[0]; shift;}

  if (($ARGV[0] >= 1) && ($ARGV[0] <= 9)){
    $level = $ARGV[0];
    printf "Level = $level\n";
    shift;
  }
}

foreach $f (@ARGV){
  # reading and writing file
  $seg=$line=$nblank=0;
  open(infile,"<$f") or die "Cannot open $f\n";

  if ($DirFlg){
    $Dir="$f.s";
    system("delete $Dir");
    mkdir $Dir;
    chdir $Dir;
    system "ln -s ../$f .";
    print "Directory $f.s created\n";
  }

  while (<infile>) {
    if ( /(\S+)/ ) {
      #non-blank line
      $nblank=0;
      if ($line==0) {
	++$seg;
	if ($TwoDFlg){
	  $n=int (($seg-1)/$TwoDN) + 1;
	  $m=($seg-1) % $TwoDN + 1;
	  $SegStr=$n."x".$m;
	}else{
	  $SegStr=$seg;
	}

	$ofile="$f.s$SegStr";
	if ($DirFlg){ $ofile="s$SegStr";} ;
	open(ofile,">$ofile") or die "Cannot open $ofile\n";
      }
      ++$line;
      print ofile "$_";
    } else {
      #blank line
      ++$nblank;
      if ($nblank>=$level) {
	$line=0;
      } else {
	print ofile "\n";	# print up to $level-1 blank lines
      }
    }
  }
  print "$f split into $seg segments\n";

  #delete extra files from previous split, if any
  ++$seg;
  while(-r "$f.s$seg"){
    unlink "$f.s$seg";
    ++$seg;
  }

  if ($DirFlg){
    unlink "$f";
  }
}
